main.pdf: main.tex 1-intro.tex 2-background.tex 3-abstractions.tex 4-schedulers.tex 5-rebuilders.tex 6-implementations.tex 7-experience.tex 8-engineering.tex 9-related.tex 10-conclusions.tex 11-appendix.tex
	pdflatex -shell-escape main.tex
